Greytyphoon.Characters.push({
    name: "Leana Thunderheart",
    flair: "eye of the everstorm",
    meta: {
        quest: "Manors & Genies",
        owner: "Grey"
    },
    flavor: {
        eyes: "brown",
        hair: "blonde",
        weight: "156 lbs",
        height: "5' 7''"
    },
    alignment: "LN",
    deity: "Pharasma",
    languages: "Common, Undercommon",
    ancestry: { name: "Human", url: "https://www.d20pfsrd.com/races/core-races/human" },
    level: [ { name: "Magus", url: "https://www.d20pfsrd.com/classes/base-classes/magus", quantity: 9 } ],
    "str": 10,
    "dex": [ 16, { points: 2, reason: "Racial" }, { points: 2, reason: "Advancement" }, { points: 2, reason: "Enhancement" } ],
    "con": 14,
    "int": [ 16, { points: 2, reason: "Enhancement" } ],
    "wis": 10,
    "cha": 10,
    traits: [
        { name: "Fate's Favored", url: "https://www.d20pfsrd.com/traits/faith-traits/fate-s-favored" },
        { name: "Magical Lineage", url: "https://www.d20pfsrd.com/traits/magic-traits/magical-lineage" }
    ],
    startingFeats: [
        { name: "Weapon Finesse", reason: "Human", url: "https://www.d20pfsrd.com/feats/combat-feats/weapon-finesse-combat-final" },
        { name: "Arcane Strike", reason: "Level 1", url: "http://www.d20pfsrd.com/feats/combat-feats/arcane-strike-combat" }
    ],
    progressFeats: [
        { name: "Weapon Focus (Rapier)", reason: "Level 3", url: "https://www.d20pfsrd.com/feats/combat-feats/weapon-focus-combat-final" },
        { name: "Flamboyant Arcana", reason: "Magus 3", url: "https://www.d20pfsrd.com/classes/base-classes/magus/magus-arcana/paizo-magus-arcana/flamboyant-arcana-ex" },
        { name: "Fencing Grace", reason: "Level 5", url: "https://www.d20pfsrd.com/feats/combat-feats/fencing-grace-combat" },
        { name: "Intensified Spell", reason: "Magus 5", url: "https://www.d20pfsrd.com/feats/metamagic-feats/intensified-spell-metamagic" },
        { name: "Arcane Deed", reason: "Magus 6", url: "https://www.d20pfsrd.com/classes/base-classes/magus/magus-arcana/paizo-magus-arcana/arcane-deed-su" },
		{ name: "Combat Reflexes", reason: "Level 7", url: "http://www.d20pfsrd.com/feats/combat-feats/combat-reflexes-combat" },
		{ name: "Lunge", reason: "Level 9", url: "http://www.d20pfsrd.com/feats/combat-feats/lunge-combat-final" },
		{ name: "Wand Wielder", reason: "Magus 9", url: "http://www.d20pfsrd.com/classes/base-classes/magus/magus-arcana/paizo---magus-arcana/wand-wielder-su" }
    ],
    targetFeats: [],
    spells: [
        { level: 0, name: "arcane mark", url: "https://www.d20pfsrd.com/magic/all-spells/a/arcane-mark", tag: "touch" },
        { level: 0, name: "detect magic", url: "https://www.d20pfsrd.com/magic/all-spells/d/detect-magic" },
        { level: 0, name: "ghost sound", url: "https://www.d20pfsrd.com/magic/all-spells/g/ghost-sound" },
        { level: 0, name: "light", url: "https://www.d20pfsrd.com/magic/all-spells/l/light", tag: "touch" },
        { level: 0, name: "mage hand", url: "https://www.d20pfsrd.com/magic/all-spells/m/mage-hand" },
        { level: 1, name: "burning hands", url: "https://www.d20pfsrd.com/magic/all-spells/b/burning-hans" },
        { level: 1, name: "chill touch", url: "https://www.d20pfsrd.com/magic/all-spells/c/chill-touch", tag: "touch" },
        { level: 1, name: "color spray", url: "https://www.d20pfsrd.com/magic/all-spells/c/color-spray" },
        { level: 1, name: "frostbite", url: "https://www.d20pfsrd.com/magic/all-spells/f/frostbite", tag: "touch" },
        { level: 1, name: "grease", url: "https://www.d20pfsrd.com/magic/all-spells/g/grease" },
        { level: 1, name: "shocking grasp", url: "https://www.d20pfsrd.com/magic/all-spells/s/shocking-grasp", tag: "touch magicalLineage" },
        { level: 1, name: "silent image", url: "https://www.d20pfsrd.com/magic/all-spells/s/silent-image" },
        { level: 1, name: "thunderstomp", url: "https://www.d20pfsrd.com/magic/all-spells/t/thunderstomp" },
        { level: 1, name: "true strike", url: "https://www.d20pfsrd.com/magic/all-spells/t/true-strike" },
        { level: 1, name: "vanish", url: "https://www.d20pfsrd.com/magic/all-spells/v/vanish" },
        { level: 1, name: "weaponwand", url: "https://www.d20pfsrd.com/magic/all-spells/w/weaponwand", tag: "durationNotStandard" },
        { level: 2, name: "bladed dash", url: "https://www.d20pfsrd.com/magic/all-spells/b/bladed-dash" },
        { level: 2, name: "frigid touch", url: "https://www.d20pfsrd.com/magic/all-spells/f/frigid-touch", tag: "touch" },
        { level: 2, name: "glitterdust", url: "https://www.d20pfsrd.com/magic/all-spells/g/glitterdust" },
        { level: 2, name: "levitate", url: "https://www.d20pfsrd.com/magic/all-spells/l/levitate" },
        { level: 2, name: "mirror image", url: "https://www.d20pfsrd.com/magic/all-spells/m/mirror-image" },
        { level: 2, name: "web", url: "https://www.d20pfsrd.com/magic/all-spells/w/web" },
        { level: 3, name: "dispel magic", url: "https://www.d20pfsrd.com/magic/all-spells/d/dispel-magic" },
        { level: 3, name: "fireball", url: "https://www.d20pfsrd.com/magic/all-spells/f/fireball" },
        { level: 3, name: "fly", url: "https://www.d20pfsrd.com/magic/all-spells/f/fly" },
        { level: 3, name: "haste", url: "https://www.d20pfsrd.com/magic/all-spells/h/haste" },
        { level: 3, name: "slow", url: "https://www.d20pfsrd.com/magic/all-spells/s/slow" },
        { level: 3, name: "vampiric touch", url: "https://www.d20pfsrd.com/magic/all-spells/v/vampiric-touch", tag: "touch" }
    ],
    loot: [
        { slot: "weapon-m", value: 8300, name: "Rapier +1 Keen", url: "http://www.d20pfsrd.com/magic-items/magic-weapons/magic-weapon-special-abilities/keen" },
        { slot: "weapon-r", value: 300, name: "Longbow [0]", url: "http://www.d20pfsrd.com/equipment/weapons" },
        { slot: "headband", value: 4000, name: "Headband of Vast Intelligence", url: "https://www.d20pfsrd.com/magic-items/wondrous-items/wondrous-items/h-l/headband-of-vast-intelligence" },
        { slot: "armor", value: 2100, name: "Mithral Shirt +1", url: "https://www.d20pfsrd.com/magic-items/magic-armor/specific-magic-armor/mithral-shirt/" },
        { slot: "shield", value: 2150, name: "Mithral Buckler +1", url: "https://www.d20pfsrd.com/equipment/special-materials#TOC-Mithral" },
        { slot: "shoulders", value: 1000, name: "Cloak of Resistance", url: "http://www.d20pfsrd.com/magic-items/wondrous-items/wondrous-items/c-d/cloak-of-resistance" },
        { slot: "body", value: 5000, name: "Tunic of Careful Casting", url: "http://www.d20pfsrd.com/magic-items/wondrous-items/wondrous-items/r-z/tunic-of-careful-casting" },
        { slot: "wrists", value: 5000, name: "Spellguard Bracers", url: "http://www.d20pfsrd.com/magic-items/wondrous-items/wondrous-items/a-b/spellguard-bracers" },
        { slot: "hands", value: 5000, name: "Gloves of Arcane Striking", url: "http://www.d20pfsrd.com/magic-items/wondrous-items/wondrous-items/e-g/gloves-of-arcane-striking" },
        { slot: "belt", value: 4000, name: "Belt of Incredible Dexterity", url: "http://www.d20pfsrd.com/magic-items/wondrous-items/wondrous-items/a-b/belt-of-incredible-dexterity" },
        { slot: "none", value: 6000, name: "Caster's Tattoo", url: "http://www.d20pfsrd.com/magic-items/wondrous-items/wondrous-items/r-z/tattoo-caster-s" },
        { slot: "none", value: 2000, name: "Handy Haversack", url: "https://www.d20pfsrd.com/magic-items/wondrous-items/wondrous-items/a-b/bag-handy-haversack" },
        { slot: "none", value: 1000, name: "Pearl of Power", url: "https://www.d20pfsrd.com/magic-items/wondrous-items/wondrous-items/m-q/pearl-of-power" },
        { slot: "none", value: 20000, name: "Stone of Good Luck", url: "https://www.d20pfsrd.com/magic-items/wondrous-items/wondrous-items/r-z/stone-of-good-luck-luckstone" },
        { slot: "none", value: 2500, name: "Swordmaster's flair", url: "http://www.d20pfsrd.com/magic-items/wondrous-items/wondrous-items/r-z/swordmaster-s-flair" }
    ]
});